In [ ]:
import numpy as np
import tensorflow as tf
import ast

In [ ]:
# Load the Drive helper and mount
from google.colab import drive

# This will prompt for authorization.
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
file_path = "/content/drive/My Drive/Colab Notebooks/interaktionDesign/game_results.txt"

with open(file_path, 'r') as file:
    content = file.read()

In [ ]:
lines = content.split('\n')
lines_tensor = tf.constant(lines)
shuffled_lines = tf.random.shuffle(lines_tensor)
print(shuffled_lines.shape)

all_inputs = []
all_labels = []
# Iteriere über jede Zeile und erstelle eine Trainingsdatei
for index, line in enumerate(shuffled_lines):
  line = line.numpy().decode('utf-8')

  input_str, label_str = line.split(';')
  input_list = np.array(ast.literal_eval(input_str))
  label = int(label_str)
  all_inputs.append(input_list)
  all_labels.append(label)

x_train = np.array(all_inputs[0:5000])  # Hier werden die Listen in numpy-Arrays umgewandelt
y_train = tf.keras.utils.to_categorical(np.array(all_labels[0:5000]), num_classes=3)

x_val = np.array(all_inputs[5000:])
y_val = tf.keras.utils.to_categorical(np.array(all_labels[5000:]), num_classes=3)

print(x_train.shape)
print(y_train.shape)


(9241,)
(5000, 9)
(5000, 3)


In [ ]:
print(y_train[2])
print(x_train[2])

[0. 0. 1.]
[1 1 2 1 0 2 2 1 2]


In [ ]:
# Define the input layer
model = tf.keras.Sequential([
  tf.keras.layers.Input(shape=[9]),
  tf.keras.layers.Dense(units=9,activation="relu"),
  tf.keras.layers.Dense(units=3, activation="softmax")
])

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(0.01), metrics=['accuracy'])

# Train the model
history = model.fit(x_train, y_train, epochs=200, verbose=1, validation_data=(x_val, y_val) )

Epoch 1/200
157/157 [==============================] - 1s 3ms/step - loss: 0.9633 - accuracy: 0.5580 - val_loss: 0.8657 - val_accuracy: 0.6032
Epoch 2/200
157/157 [==============================] - 0s 3ms/step - loss: 0.8484 - accuracy: 0.6034 - val_loss: 0.8215 - val_accuracy: 0.6041
Epoch 3/200
157/157 [==============================] - 0s 2ms/step - loss: 0.8117 - accuracy: 0.6044 - val_loss: 0.7958 - val_accuracy: 0.6081
Epoch 4/200
157/157 [==============================] - 0s 3ms/step - loss: 0.7899 - accuracy: 0.6134 - val_loss: 0.7720 - val_accuracy: 0.6067
Epoch 5/200
157/157 [==============================] - 0s 2ms/step - loss: 0.7764 - accuracy: 0.6120 - val_loss: 0.7624 - val_accuracy: 0.6237
Epoch 6/200
157/157 [==============================] - 0s 3ms/step - loss: 0.7611 - accuracy: 0.6254 - val_loss: 0.7414 - val_accuracy: 0.6409
Epoch 7/200
157/157 [==============================] - 0s 3ms/step - loss: 0.7550 - accuracy: 0.6272 - val_loss: 0.7374 - val_accuracy: 0.6359

In [ ]:
print(model.predict([(2,1,1,1,2,2,2,2,2)]))

1/1 [==============================] - 0s 32ms/step
[[0.13503435 0.5060102  0.35895544]]
